services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "11434:11434"
    volumes:
      - .:/app
    depends_on:
      - api


  api:
    image: ollama/ollama
    ports:
      - "11434:11434"
