services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
      # - "80:80"
    volumes:
      - .:/app
    depends_on:
      - api


  api:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    command: "sh ollama run deepseek-r1:1.5b"


volumes:
  ollama:
